### PR TITLE
Update Ubuntu summit logo

### PR DESCRIPTION
**Pull request by carkod**

### CODE REVIEW

**Comment by kewisch** [comment]
Changing it in this way would change it both for Ubuntu Summit 2022 and 2023, I believe. We'll either have to do a copy of the theme, or make it conditional. This might also need some refactoring of the theme as well so we don't have two copies.

**Comment by carkod** [comment]
> Changing it in this way would change it both for Ubuntu Summit 2022 and 2023, I believe. We'll either have to do a copy of the theme, or make it conditional. This might also need some refactoring of the theme as well so we don't have two copies.


> Changing it in this way would change it both for Ubuntu Summit 2022 and 2023, I believe. We'll either have to do a copy of the theme, or make it conditional. This might also need some refactoring of the theme as well so we don't have two copies.

It looks like the new logo is already there? https://events.canonical.com/event/31/

**Comment by kewisch** [comment]
For that we're using the theme with a simple orange gradient, and using indico's header image to add just the centerpiece. It doesn't have the circle lines.

**Comment by carkod** [comment]
Ok, I think the task I was supposed to do was not this

**Pull request closed without merging**
