### PR TITLE
Revert logo changes

### PR DESCRIPTION
**Pull request by petesfrench**

### CODE REVIEW

**Comment by petesfrench** [comment]
@kewisch Could you take a look at this please?

**Comment by kewisch** [comment]
@petesfrench this change seems to just be changing the form css, not the actual logo. Am I missing something?

**Comment by petesfrench** [comment]
@kewisch Apologies, I had pushed the wrong branch. Can you take another look please?

**Review by kewisch — APPROVED** [review]
LGTM

**Pull request merged**
