### PR TITLE
Update call for abstracts page

### PR DESCRIPTION
**Pull request by petesfrench**
### Done

Update call for abstracts page & form

### QA
To QA you will need to open 'call for abstracts' (CfA). This can be found in the event management section of the running Indico Instance.
Under 'Workflows', select 'Call for Abstracts' and click 'Open'.
Now go back to the page and you will see 'Call for Abstracts' in the side column.
- Check the 'CfA' landing page.
- Try to submit an abstract and test the different functionalities of the form.

### Fixes
https://github.com/canonical/web-squad/issues/5690

### CODE REVIEW

**Review by carkod — APPROVED** [review]
LGTM.

But I'd check browser stack at the end, see that everything works well across browsers, because the amount of cool new CSS properties is considerable

**Comment by petesfrench** [comment]
@carkod Thank you for the review! What properties do I need to be careful with?

**Comment by carkod** [comment]
> @carkod Thank you for the review! What properties do I need to be careful with?

Well, I actually checked them in [caniuse](https://caniuse.com/) and there seems to be good support overall. So just to make sure that there is nothing weird or broken.

**Comment by petesfrench** [comment]
> The `var();` functions are an interesting one. I think if we have functions like this that are well supported, then we don't need SASS anymore? So I'm just wondering if they have good support in other browsers.

From what I read var() is supported across all modern browsers except IE, which we don't support anyway. SASS gives us variables but also access to mixins, more types of selector, mathematical functions etc. While CSS is going that way, it isn't there yet and wide browser support is a ways off.

**Pull request merged**
